services:
  postgres:
    image: postgres:16
    container_name: compose-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ecapi
      POSTGRES_USER: ecapi_user
      POSTGRES_PASSWORD: ecapi_pw

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecapi_user -d ecapi"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
