"""add endpoints and services

Revision ID: 04ebdfaf4304
Revises: c3fd04c560ae
Create Date: 2026-05-20

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "04ebdfaf4304"
down_revision: Union[str, None] = "c3fd04c560ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endpoint_types",
        sa.Column("type_id", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("type_id"),
    )
    op.create_table(
        "service_types",
        sa.Column("type_id", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("type_id"),
    )
    op.create_table(
        "endpoints",
        sa.Column("endpoint_id", sa.Text(), nullable=False),
        sa.Column("type_id", sa.Text(), nullable=False),
        sa.Column(
            "endpoint_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["endpoint_types.type_id"],
        ),
        sa.PrimaryKeyConstraint("endpoint_id"),
    )
    op.create_table(
        "services",
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("type_id", sa.Text(), nullable=False),
        sa.Column(
            "service_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["service_types.type_id"],
        ),
        sa.PrimaryKeyConstraint("service_id"),
    )
    op.alter_column(
        "active_deployment",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        op.f("password_renewal_tasks_device_id_fkey"),
        "password_renewal_tasks",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "password_renewal_tasks", "devices", ["device_id"], ["device_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.create_foreign_key(
        op.f("password_renewal_tasks_device_id_fkey"),
        "password_renewal_tasks",
        "devices",
        ["device_id"],
        ["device_id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "active_deployment",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_table("services")
    op.drop_table("endpoints")
    op.drop_table("service_types")
    op.drop_table("endpoint_types")
    # ### end Alembic commands ###
